"""add duplicate status and duplicate_of

Revision ID: c226637b32c1
Revises: 35920f8a52f7
Create Date: 2026-08-02 12:54:08.371702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c226637b32c1'
down_revision: Union[str, Sequence[str], None] = '35920f8a52f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('duplicate_of_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'duplicate_of_id')
    # ### end Alembic commands ###
